version: 2.1
jobs:
  build:
    docker:
    - image: circleci/python:3.8.2
    working_directory: ~/workspace
    steps:
    - checkout
    - run:
        name: Create virtual env
        command: |
            python3 -m venv .venv
            echo "source .venv/bin/activate" >> $BASH_ENV

    - run:
        name: Run unit tests
        command: |
            python -m pip install .
            python -m unittest test/test_fibonacci.py
workflows:
  build:
    jobs:
    - build



